version: '3'

services:

  intellead-connector:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-connector
    ports:
     - "3001:3000"
    networks:
     - web
     - mongo

  intellead-fitscore:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-fitscore
    ports:
     - "3002:5000"
    networks:
     - web

  intellead-data:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-data
    ports:
     - "3003:3000"
    networks:
     - web
     - mongo

  intellead-enrich:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-enrich
    ports:
     - "3004:3000"
    networks:
     - web

  receitaws-data:
    build:
      context: ./docker
      dockerfile: Dockerfile-receitaws-data
    ports:
     - "3005:3000"
    networks:
     - web

  qcnpj-crawler:
    build:
      context: ./docker
      dockerfile: Dockerfile-qcnpj-crawler
    ports:
     - "3006:3000"
    networks:
     - web

  intellead-classification:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-classification
    ports:
     - "3007:5000"
    networks:
     - web
     - postgres

  intellead-data-mongodb:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-data-mongodb
    ports:
     - "4001:27017"
    networks:
     - mongo

  intellead-classification-postgresql:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-classification-postgresql
    ports:
     - "4002:5432"
    networks:
     - postgres

  intellead-integration-tests:
    build: .
    networks:
     - web
     - postgres
     - mongo
    depends_on:
     - intellead-connector
     - intellead-fitscore
     - intellead-data
     - intellead-enrich
     - receitaws-data
     - qcnpj-crawler
     - intellead-classification
     - intellead-data-mongodb
     - intellead-classification-postgresql
    environment:
     - INTELLEAD_CONNECTOR_URL=intellead-connector:3000
     - INTELLEAD_FITSCORE_URL=intellead-fitscore:5000
     - INTELLEAD_DATA_URL=intellead-data:3000
     - INTELLEAD_ENRICH_URL=intellead-enrich:3000
     - RECEITAWS_DATA_URL=receitaws-data:3000
     - QCNPJ_CRAWLER_URL=qcnpj-crawler:3000
     - INTELLEAD_CLASSIFICATION_URL=intellead-classification:5000
     - INTELLEAD_DATA_MONGODB_HOST=intellead-data-mongodb
     - INTELLEAD_DATA_MONGODB_PORT=27017
     - INTELLEAD_CLASSIFICATION_POSTGRESQL_HOST=intellead-classification-postgresql
     - INTELLEAD_CLASSIFICATION_POSTGRESQL_PORT=5432

networks:
  web:
    driver: bridge
  postgres:
    driver: bridge
  mongo:
    driver: bridge