version: '3'

services:

  intellead-connector:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-connector
    networks:
      - web
      - mongo_data

  intellead-security:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-security
    networks:
      - web
      - postgres_security

  intellead-data:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-data
    networks:
      - web
      - mongo_data

  intellead-enrich:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-enrich
    networks:
      - web

  receitaws-data:
    build:
      context: ./docker
      dockerfile: Dockerfile-receitaws-data
    networks:
      - web

  qcnpj-crawler:
    build:
      context: ./docker
      dockerfile: Dockerfile-qcnpj-crawler
    networks:
      - web

  intellead-classification:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-classification
    networks:
      - web
      - postgres_classification

  intellead-normalization:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-normalization
    networks:
      - web
      - postgres_normalization

  intellead-security-postgresql:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-security-postgresql
    networks:
      - postgres_security

  intellead-data-mongodb:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-data-mongodb
    networks:
      - mongo_data

  intellead-classification-postgresql:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-classification-postgresql
    networks:
      - postgres_classification

  intellead-normalization-postgresql:
    build:
      context: ./docker
      dockerfile: Dockerfile-intellead-normalization-postgresql
    networks:
      - postgres_normalization

  intellead-integration-tests:
    build: .
    networks:
      - web
      - postgres_classification
      - postgres_normalization
      - postgres_security
      - mongo_data
    depends_on:
      - intellead-connector
      - intellead-data
      - intellead-enrich
      - receitaws-data
      - qcnpj-crawler
      - intellead-classification
      - intellead-normalization
      - intellead-security
      - intellead-data-mongodb
      - intellead-classification-postgresql
      - intellead-normalization-postgresql
      - intellead-security-postgresql
    environment:
      - INTELLEAD_CONNECTOR_URL=intellead-connector:3000
      - INTELLEAD_DATA_URL=intellead-data:3000
      - INTELLEAD_ENRICH_URL=intellead-enrich:3000
      - RECEITAWS_DATA_URL=receitaws-data:3000
      - QCNPJ_CRAWLER_URL=qcnpj-crawler:3000
      - INTELLEAD_CLASSIFICATION_URL=intellead-classification:5000
      - INTELLEAD_DATA_MONGODB_HOST=intellead-data-mongodb
      - INTELLEAD_DATA_MONGODB_PORT=27017
      - INTELLEAD_CLASSIFICATION_POSTGRESQL_HOST=intellead-classification-postgresql
      - INTELLEAD_CLASSIFICATION_POSTGRESQL_PORT=5432

networks:
  web:
    driver: bridge
  postgres_classification:
    driver: bridge
  mongo_data:
    driver: bridge
  postgres_security:
    driver: bridge
  postgres_normalization:
    driver: bridge