FROM python:3.6.2

WORKDIR /usr/src/intellead

RUN apt-get install git && \
    git clone https://github.com/softplan/intellead-fitscore.git

WORKDIR /usr/src/intellead/intellead-fitscore

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 5000

CMD [ "python", "./app.py" ]