FROM node:8.6.0-alpine

WORKDIR /usr/src/intellead

RUN apt-get install git && \
    git clone https://github.com/intellead/qcnpj-crawler.git

WORKDIR /usr/src/intellead/qcnpj-crawler

RUN npm install --silent --progress=false --production

EXPOSE 3000

CMD ["npm", "start"]