FROM node:8.6.0-alpine

WORKDIR /usr/src/intellead

RUN apk update && \
    apk add git && \
    apk add python make g++ && \
    git clone https://github.com/intellead/intellead-normalization.git

WORKDIR /usr/src/intellead/intellead-normalization

RUN npm install --silent --progress=false --production

EXPOSE 3000

CMD ["npm", "start"]