FROM maven:3.5.0-jdk-8-alpine

WORKDIR /usr/src/intellead

RUN apk update && \
    apk add git && \
    git clone https://github.com/softplan/intellead-security.git

WORKDIR /usr/src/intellead/intellead-security

RUN rm application.yml && \
    mv src/main/resources/application-docker.yml src/main/resources/application.yml

RUN mvn clean compile package

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "target/intellead-security-1.0-SNAPSHOT.jar"]