FROM node:8.6.0-alpine

WORKDIR /usr/src/intellead

RUN apk update && \
    apk add git && \
    git clone https://github.com/softplan/receitaws-data.git

WORKDIR /usr/src/intellead/receitaws-data

RUN npm install --silent --progress=false --production

EXPOSE 3000

CMD ["npm", "start"]